### ISSUE TITLE
TransMorph_DCA for IXI

### ISSUE THREAD

**Issue by huaibovip** [junyuchen245/TransMorph_DCA#1]
Thanks for sharing your valuable work.
  I'm having trouble porting TransMorphDCA to IXI dataset, would it be convenient for you to provide an implementation of TransMorphDCA on the IXI dataset? I would be very grateful if you could provide the source code!
My E-mail: huaibovip@gmail.com

**Comment by junyuchen245** [comment]
Hi @huaibovip ,

I've made updates to the repository and added the source code related to the IXI dataset.

Junyu

**Comment by huaibovip** [comment]
Thanks! @junyuchen245
